use std::io::{self, Write};

use chrono::{Datelike, Timelike, Utc};

use crate::types::{Track, TrackPoint};

// `A` record for files regenerated by Tengri; `XXX` is the generic manufacturer code.
const LOGGER_ID: &str = "AXXXTENGRI";
const FIRST_EXTENSION_BYTE: usize = 36;
const MIN_TAS_WIDTH: usize = 3;

pub fn write<W: Write>(mut writer: W, track: &Track) -> io::Result<()> {
    // IGC HFDTE dates and B-record times are UTC, matching our Unix timestamps.
    let start = chrono::DateTime::<Utc>::from_timestamp(i64::from(track.start_time), 0)
        .ok_or_else(|| {
            io::Error::new(io::ErrorKind::InvalidInput, "track start time out of range")
        })?;
    writeln!(writer, "{LOGGER_ID}")?;
    writeln!(
        writer,
        "HFDTE{:02}{:02}{:02}",
        start.day(),
        start.month(),
        start.year().rem_euclid(100)
    )?;

    let tas_width = tas_width(track);
    if let Some(width) = tas_width {
        writeln!(
            writer,
            "I01{FIRST_EXTENSION_BYTE:02}{:02}TAS",
            FIRST_EXTENSION_BYTE + width - 1
        )?;
    }

    for point in &track.points {
        write_b_record(&mut writer, *point, tas_width)?;
    }
    Ok(())
}

// A B-record is one GPS fix: UTC time, lat/lon, fix validity, pressure
// altitude, GPS altitude, plus optional fields declared by an I-record.
fn write_b_record<W: Write>(
    writer: &mut W,
    point: TrackPoint,
    tas_width: Option<usize>,
) -> io::Result<()> {
    let timestamp = chrono::DateTime::<Utc>::from_timestamp(i64::from(point.time), 0)
        .ok_or_else(|| io::Error::new(io::ErrorKind::InvalidInput, "point time out of range"))?;
    let (lat_deg, lat_min_thousandths, lat_hemi) = format_lat(point.lat);
    let (lon_deg, lon_min_thousandths, lon_hemi) = format_lon(point.lon);
    let pressure_alt_m = point.pressure_alt.unwrap_or(0) / 10;
    let geo_alt_m = point.geo_alt / 10;

    write!(
        writer,
        "B{:02}{:02}{:02}{lat_deg:02}{lat_min_thousandths:05}{lat_hemi}{lon_deg:03}{lon_min_thousandths:05}{lon_hemi}A{pressure_alt_m:05}{geo_alt_m:05}",
        timestamp.hour(),
        timestamp.minute(),
        timestamp.second(),
    )?;
    if let Some(width) = tas_width {
        let tas = point.tas.ok_or_else(|| {
            io::Error::new(
                io::ErrorKind::InvalidInput,
                "TAS is not present on every point",
            )
        })?;
        write!(writer, "{tas:0width$}")?;
    }
    writeln!(writer)
}

fn format_lat(lat_e5: i32) -> (i32, i32, char) {
    let hemi = if lat_e5 < 0 { 'S' } else { 'N' };
    let (deg, min_thousandths) = format_coord(lat_e5);
    (deg, min_thousandths, hemi)
}

fn format_lon(lon_e5: i32) -> (i32, i32, char) {
    let hemi = if lon_e5 < 0 { 'W' } else { 'E' };
    let (deg, min_thousandths) = format_coord(lon_e5);
    (deg, min_thousandths, hemi)
}

fn format_coord(e5: i32) -> (i32, i32) {
    let abs = i64::from(e5).abs();
    let deg = abs / 100_000;
    let rest_e5 = abs % 100_000;
    let min_thousandths = (rest_e5 * 60_000 + 50_000) / 100_000;
    (
        (deg + min_thousandths / 60_000) as i32,
        (min_thousandths % 60_000) as i32,
    )
}

fn tas_width(track: &Track) -> Option<usize> {
    if track.points.is_empty() || track.points.iter().any(|point| point.tas.is_none()) {
        return None;
    }
    track
        .points
        .iter()
        .filter_map(|point| point.tas)
        .map(decimal_width)
        .max()
        .map(|width| width.max(MIN_TAS_WIDTH))
}

fn decimal_width(value: u16) -> usize {
    value.to_string().len()
}

#[cfg(test)]
mod tests {
    use crate::{
        igc::parse_str,
        types::{Track, TrackPoint},
    };

    use super::write;

    #[test]
    fn writes_parseable_igc() {
        let track = Track {
            start_time: 1_775_297_673,
            points: vec![
                TrackPoint {
                    time: 1_775_297_673,
                    lat: 4_310_075,
                    lon: -7_602_512,
                    geo_alt: 9_810,
                    pressure_alt: Some(0),
                    tas: Some(42),
                },
                TrackPoint {
                    time: 1_775_297_733,
                    lat: -4_310_275,
                    lon: 7_603_012,
                    geo_alt: -120,
                    pressure_alt: Some(-50),
                    tas: Some(1_234),
                },
            ],
        };
        let mut out = Vec::new();

        write(&mut out, &track).expect("write");
        let parsed = parse_str(std::str::from_utf8(&out).expect("utf8")).expect("parse");

        assert_eq!(parsed.points.len(), track.points.len());
        assert_eq!(parsed.points[0].time, track.points[0].time);
        assert_eq!(parsed.points[0].lat, 4_310_075);
        assert_eq!(parsed.points[0].lon, -7_602_512);
        assert_eq!(parsed.points[1].geo_alt, -120);
        assert_eq!(parsed.points[1].pressure_alt, Some(-50));
        assert_eq!(parsed.points[0].tas, Some(42));
        assert_eq!(parsed.points[1].tas, Some(1_234));
    }
}
