-- Initial schema: users, flights, derived tracks, source uploads.
-- See db schema plan for rationale; this file is the authoritative SQL.

CREATE TYPE flight_track_kind AS ENUM ('full', 'preview');

CREATE TYPE flight_source_format AS ENUM ('igc', 'gpx', 'kml');


CREATE TABLE users (
    id   int  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE
);


-- `id` is an 8-char NanoID generated in Rust on insert (alphabet [A-Za-z0-9_-]).
-- Stored as `text` rather than `varchar(8)` so we never pay the length-check
-- overhead; we trust the generator. Equality lookups on text use byte-wise
-- comparison regardless of collation, so PK/FK lookups match uuid speed.
CREATE TABLE flights (
    id         text        PRIMARY KEY,
    user_id    int         NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    created_at timestamptz NOT NULL DEFAULT now()
);

-- Per-user flight listing ("user X's flights, newest first").
CREATE INDEX flights_user_created_idx ON flights (user_id, created_at DESC);

-- Global feed ("latest flights across all users"). Cannot be served by the
-- composite index above because user_id is its leading column.
CREATE INDEX flights_created_idx ON flights (created_at DESC);


-- Hot path: compact-format track blobs (full + preview) per flight.
--
-- `bytes` stores the HTTP wire form: `gzip(bincode(TengriFile))`. We serve it
-- straight to the client with `Content-Encoding: gzip`, so the on-disk row is
-- byte-identical to the response body — zero CPU per request.
--
-- `version` mirrors `TengriFile::VERSION` at the time `bytes` was written.
-- It's queryable so a re-encoding cron task can find rows that lag behind the
-- current build (`WHERE version < $current`) without touching the blob.
--
-- `etag` is xxh3-64 of `bytes` (16 hex chars), regenerated on every write.
-- Used as the HTTP `ETag` for `If-None-Match` / 304 handling.
CREATE TABLE flight_tracks (
    flight_id text              NOT NULL REFERENCES flights(id) ON DELETE CASCADE,
    kind      flight_track_kind NOT NULL,
    version   smallint          NOT NULL,
    etag      text              NOT NULL,
    bytes     bytea             NOT NULL,
    PRIMARY KEY (flight_id, kind)
);


-- Cold path: gzipped original upload bytes. One per flight.
-- No filename column on purpose: download paths synthesize "<flight_id>.<format>"
-- so user-supplied strings never reach Content-Disposition.
CREATE TABLE flight_sources (
    flight_id text                 PRIMARY KEY REFERENCES flights(id) ON DELETE CASCADE,
    format    flight_source_format NOT NULL,
    bytes     bytea                NOT NULL
);
