-- Initial schema: users, flights, derived tracks, source uploads.
-- See db schema plan for rationale; this file is the authoritative SQL.

CREATE TYPE flight_track_kind AS ENUM ('full', 'preview');

CREATE TYPE flight_source_format AS ENUM ('igc', 'gpx', 'kml');


CREATE TABLE users (
    id   int  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE
);


-- `id` is an 8-char NanoID generated in Rust on insert (alphabet [A-Za-z0-9_-]).
-- Stored as `text` rather than `varchar(8)` so we never pay the length-check
-- overhead; we trust the generator. Equality lookups on text use byte-wise
-- comparison regardless of collation, so PK/FK lookups match uuid speed.
--
-- `takeoff_at` / `landed_at` are derived at ingest time by
-- `tengri_server::flight::find_flight_window` over the parsed track.
--
-- `duration_s` is a Postgres-maintained generated column (`landed_at -
-- takeoff_at` in whole seconds). Sortable / filterable directly without
-- an expression index. `integer` (max ~68 years) is plenty: even a
-- 16-hour XC flight is ~58 000 s.
CREATE TABLE flights (
    id         text        PRIMARY KEY,
    user_id    int         NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    created_at timestamptz NOT NULL DEFAULT now(),
    takeoff_at timestamptz NOT NULL,
    landed_at  timestamptz NOT NULL,
    duration_s integer     NOT NULL GENERATED ALWAYS AS (
        EXTRACT(EPOCH FROM (landed_at - takeoff_at))::integer
    ) STORED
);

-- Per-user flight listing ("user X's flights, newest first" — by flight time,
-- not ingest time). takeoff_at is the natural sort key; created_at is just
-- when the row landed in the DB.
CREATE INDEX flights_user_takeoff_idx ON flights (user_id, takeoff_at DESC);

-- Global feed ("latest flights across all users", by takeoff_at). Cannot be
-- served by the composite index above because user_id is its leading column.
CREATE INDEX flights_takeoff_idx ON flights (takeoff_at DESC);

-- Admin / ingest views: "what got uploaded recently". Different question
-- from "when did the flight happen", so a separate index.
CREATE INDEX flights_created_idx ON flights (created_at DESC);


-- Hot path: compact-format track blobs (full + preview) per flight.
--
-- `bytes` stores the HTTP wire form: `gzip(bincode(TengriFile))`. We serve it
-- straight to the client with `Content-Encoding: gzip`, so the on-disk row is
-- byte-identical to the response body — zero CPU per request.
--
-- `version` mirrors `TengriFile::VERSION` at the time `bytes` was written.
-- It's queryable so a re-encoding cron task can find rows that lag behind the
-- current build (`WHERE version < $current`) without touching the blob.
--
-- `etag` is xxh3-64 of `bytes` (16 hex chars), regenerated on every write.
-- Used as the HTTP `ETag` for `If-None-Match` / 304 handling.
--
-- `compression_ratio` is `length(flight_tracks.bytes) /
-- length(flight_sources.bytes)` captured at write time — i.e. our compact
-- format vs gzipped source. Smaller is better; e.g. 0.18 means the wire
-- track is 18% the size of the gzipped original. The denominator is always
-- gzipped, so the metric stays meaningful when source formats expand
-- beyond IGC (GPX/KML are XML and gzip far worse than IGC, so future
-- ratios will look better against those even with the same encoder).
-- Recomputed by `tengri upgrade-tracks` whenever a row is re-encoded.
CREATE TABLE flight_tracks (
    flight_id         text              NOT NULL REFERENCES flights(id) ON DELETE CASCADE,
    kind              flight_track_kind NOT NULL,
    version           smallint          NOT NULL,
    etag              text              NOT NULL,
    bytes             bytea             NOT NULL,
    compression_ratio real              NOT NULL,
    PRIMARY KEY (flight_id, kind)
);


-- Cold path: gzipped original upload bytes. One per flight.
-- No filename column on purpose: download paths synthesize "<flight_id>.<format>"
-- so user-supplied strings never reach Content-Disposition.
CREATE TABLE flight_sources (
    flight_id text                 PRIMARY KEY REFERENCES flights(id) ON DELETE CASCADE,
    format    flight_source_format NOT NULL,
    bytes     bytea                NOT NULL
);
