-- New glider data model: canonical brands + models, per-wing `gliders` rows,
-- and per-flight propulsion / launch method. See docs/gliders.md for the design
-- rationale (resolution flow, why text and FK don't coexist, why the trigger
-- exists).
--
-- Brand and model PKs are text slugs derived from the display name (lowercase,
-- diacritics stripped, non-alphanumeric runs collapsed to `-`). Slugs read
-- naturally in foreign keys (`brand_id = 'aeros'`); renames cascade through `ON
-- UPDATE CASCADE` instead of requiring per-row UPDATEs.
--
-- Wipes every existing flight (and its track / source blobs) because the new
-- shape can't be backfilled from what we have. Users untouched.

TRUNCATE flights CASCADE;


CREATE TYPE glider_kind AS ENUM ('pg', 'hg', 'sp', 'other');

-- Polymorphic class enum: PG cert tiers, HG airframe shapes, FAI sailplane comp
-- classes. Per-table CHECKs tie each value to its compatible `kind`, so EN-B on
-- a hang-glider fails.
CREATE TYPE glider_class AS ENUM (
    -- PG
    'en_a', 'en_b', 'en_c', 'en_d', 'ccc',
    -- HG
    'single_surface', 'kingpost', 'topless', 'rigid',
    -- SP
    'standard', 'fifteen_metre', 'eighteen_metre',
    'twenty_metre_two_seater', 'open', 'club', 'motorglider'
);

CREATE TYPE propulsion AS ENUM ('free', 'self_launch', 'powered');

CREATE TYPE launch_method AS ENUM ('foot', 'winch', 'aerotow');


CREATE TABLE brands (
    id   text PRIMARY KEY,           -- slug, e.g. "aeros", "wills-wing"
    name text NOT NULL UNIQUE        -- display, e.g. "Aeros", "Wills Wing"
);


-- `kind` is part of the PK because a brand can legitimately reuse a model
-- name across kinds (e.g. APCO Aviation made both an HG and a PG named
-- "Santana"). Including `kind` in the composite FK from `gliders` also makes
-- the FK enforce `gliders.kind = glider_models.kind` for resolved rows — no
-- separate sync needed for the `kind` column.
CREATE TABLE glider_models (
    brand_id  text         NOT NULL REFERENCES brands(id)
                                       ON UPDATE CASCADE ON DELETE RESTRICT,
    kind      glider_kind  NOT NULL,
    id        text         NOT NULL,           -- slug within (brand, kind), e.g. "combat-l-07"
    name      text         NOT NULL,           -- display, e.g. "Combat L 07"
    class     glider_class NOT NULL,
    is_tandem boolean      NOT NULL DEFAULT FALSE,

    PRIMARY KEY (brand_id, kind, id),
    UNIQUE (brand_id, kind, name),

    CONSTRAINT glider_models_class_matches_kind CHECK (
        (kind = 'pg' AND class IN ('en_a','en_b','en_c','en_d','ccc')) OR
        (kind = 'hg' AND class IN ('single_surface','kingpost','topless','rigid')) OR
        (kind = 'sp' AND class IN ('standard','fifteen_metre','eighteen_metre',
                                    'twenty_metre_two_seater','open','club','motorglider'))
    ),

    -- The 20m-two-seater FAI class is by definition two-seater.
    CONSTRAINT glider_models_two_seater_implies_tandem CHECK (
        class IS DISTINCT FROM 'twenty_metre_two_seater' OR is_tandem
    )
);


-- One row per (deduped) wing we've actually seen. Nullable FKs record "unknown
-- brand and/or model" without a magic Unknown row; `*_text` columns hold raw
-- uploader strings when the FK didn't resolve. The composite (brand_id,
-- model_id) FK uses MATCH SIMPLE so it's enforced only when both columns are
-- non-null (brand-only resolution stays legal).
CREATE TABLE gliders (
    id         int          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind       glider_kind  NOT NULL,
    class      glider_class,
    is_tandem  boolean,
    brand_id   text         REFERENCES brands(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    brand_text text,
    model_id   text,
    model_text text,

    FOREIGN KEY (brand_id, kind, model_id)
        REFERENCES glider_models (brand_id, kind, id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT gliders_model_implies_brand CHECK (
        model_id IS NULL OR brand_id IS NOT NULL
    ),
    CONSTRAINT gliders_brand_text_xor_fk CHECK (
        brand_id IS NULL OR brand_text IS NULL
    ),
    CONSTRAINT gliders_model_text_xor_fk CHECK (
        model_id IS NULL OR model_text IS NULL
    ),
    CONSTRAINT gliders_class_matches_kind CHECK (
        class IS NULL OR
        (kind = 'pg' AND class IN ('en_a','en_b','en_c','en_d','ccc')) OR
        (kind = 'hg' AND class IN ('single_surface','kingpost','topless','rigid')) OR
        (kind = 'sp' AND class IN ('standard','fifteen_metre','eighteen_metre',
                                    'twenty_metre_two_seater','open','club','motorglider'))
    ),
    CONSTRAINT gliders_two_seater_implies_tandem CHECK (
        class IS DISTINCT FROM 'twenty_metre_two_seater' OR is_tandem IS TRUE
    )
);

CREATE INDEX gliders_model_idx ON gliders (brand_id, model_id);
CREATE INDEX gliders_brand_idx ON gliders (brand_id);


-- Keep denormalised `class / is_tandem` on `gliders` in sync when an admin
-- re-classifies a canonical model (e.g. EN-B → EN-C on re-cert). `kind` is in
-- the composite FK from `gliders.kind` to `glider_models.kind`, so it
-- propagates via ON UPDATE CASCADE without a trigger.
CREATE FUNCTION sync_glider_denorm() RETURNS trigger AS $$
BEGIN
    UPDATE gliders
       SET class     = NEW.class,
           is_tandem = NEW.is_tandem
     WHERE brand_id = NEW.brand_id
       AND kind     = NEW.kind
       AND model_id = NEW.id;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER sync_glider_denorm
    AFTER UPDATE OF class, is_tandem ON glider_models
    FOR EACH ROW
    EXECUTE FUNCTION sync_glider_denorm();


ALTER TABLE flights
    ADD COLUMN glider_id     int           NOT NULL REFERENCES gliders(id) ON DELETE RESTRICT,
    ADD COLUMN propulsion    propulsion    NOT NULL DEFAULT 'free',
    ADD COLUMN launch_method launch_method NOT NULL DEFAULT 'foot';

CREATE INDEX flights_glider_idx ON flights (glider_id);
