-- Known launch/landing sites (takeoffs, aerodromes). Location is a
-- geography(Point, 4326) so "closest site to this fix" is a GiST KNN lookup
-- (ORDER BY point <-> $fix LIMIT 1), same pattern as flights.takeoff_point
-- (0007). Separate numeric lat/lng columns would need expression indices and
-- hand-rolled distance maths.

CREATE TABLE sites (
    id      int                    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    text                   NOT NULL,
    point   geography(Point, 4326) NOT NULL,
    -- ISO 3166-1 alpha-2 (uppercase), same shape as user_profiles.country.
    -- Nullable: no coordinate->country lookup exists yet; populated later
    -- (e.g. alongside a Natural Earth boundaries table) or by import.
    country char(2)
);

-- Spatial filters / nearest-site KNN land on the index. GiST (not BRIN)
-- because rows are not stored in geographic order.
CREATE INDEX sites_point_gix ON sites USING gist (point);

-- Seed sites. Coordinates given as (lng, lat); ST_MakePoint takes the same
-- order. id is left to IDENTITY.
INSERT INTO sites (name, country, point) VALUES
    ('Ruhpolding', 'DE', ST_SetSRID(ST_MakePoint(12.638580, 47.728430), 4326)),
    ('Kössen',     'AT', ST_SetSRID(ST_MakePoint(12.431958, 47.631685), 4326)),
    ('Chabre',     'FR', ST_SetSRID(ST_MakePoint(5.765679,  44.298264), 4326)),
    ('Apôtre',     'FR', ST_SetSRID(ST_MakePoint(5.713186,  44.541000), 4326)),
    ('Montsec',    'ES', ST_SetSRID(ST_MakePoint(0.746233,  42.046203), 4326));
