export const routes = {
  home: () => '/',
  flights: () => '/flights',
  login: () => '/login',
  resetPassword: () => '/reset-password',
  flight: (id: string) => `/flight/${id}`,
  compare: (ids: string[]) => `/compare/${ids.join(',')}`,
  terms: () => '/terms',
  privacy: () => '/privacy',
  settings: {
    index: () => '/settings',
    profile: () => '/settings/profile',
    preferences: () => '/settings/preferences',
    authorization: () => '/settings/authorization',
    stats: () => '/settings/stats',
    myFlights: () => '/settings/my-flights',
    myGliders: () => '/settings/my-gliders',
    system: () => '/settings/system',
    email: () => '/settings/email',
    oauthProviders: () => '/settings/oauth-providers',
    users: () => '/settings/users',
    gliders: () => '/settings/gliders',
    sites: () => '/settings/sites',
  },
};
